In [28]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [29]:
from sklearn.model_selection import cross_val_score,KFold
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import StandardScaler,OneHotEncoder
from xgboost import XGBClassifier
import warnings
warnings.filterwarnings("ignore") 

print("="*30)
print("Requiered Libraries Imported")
print("="*30)

==============================
Requiered Libraries Imported
==============================

In [30]:
train=pd.read_csv("train.csv")
test=pd.read_csv("test.csv")

In [31]:
train.head(5)

,id,Age,Sex,Chest pain type,BP,Cholesterol,FBS over 120,EKG results,Max HR,Exercise angina,ST depression,Slope of ST,Number of vessels fluro,Thallium,Heart Disease
0,0,58,1,4,152,239,0,0,158,1,3.6,2,2,7,Presence
1,1,52,1,1,125,325,0,2,171,0,0.0,1,0,3,Absence
2,2,56,0,2,160,188,0,2,151,0,0.0,1,0,3,Absence
3,3,44,0,3,134,229,0,2,150,0,1.0,2,0,3,Absence
4,4,58,1,4,140,234,0,2,125,1,3.8,2,3,3,Presence

In [32]:
test.head(5)

,id,Age,Sex,Chest pain type,BP,Cholesterol,FBS over 120,EKG results,Max HR,Exercise angina,ST depression,Slope of ST,Number of vessels fluro,Thallium
0,630000,58,1,3,120,288,0,2,145,1,0.8,2,3,3
1,630001,55,0,2,120,209,0,0,172,0,0.0,1,0,3
2,630002,54,1,4,120,268,0,0,150,1,0.0,2,3,7
3,630003,44,0,3,112,177,0,0,168,0,0.9,1,0,3
4,630004,43,1,1,138,267,0,0,163,0,1.8,2,0,7

In [33]:
train.isnull().sum(),test.isnull().sum()

(id                         0
 Age                        0
 Sex                        0
 Chest pain type            0
 BP                         0
 Cholesterol                0
 FBS over 120               0
 EKG results                0
 Max HR                     0
 Exercise angina            0
 ST depression              0
 Slope of ST                0
 Number of vessels fluro    0
 Thallium                   0
 Heart Disease              0
 dtype: int64,
 id                         0
 Age                        0
 Sex                        0
 Chest pain type            0
 BP                         0
 Cholesterol                0
 FBS over 120               0
 EKG results                0
 Max HR                     0
 Exercise angina            0
 ST depression              0
 Slope of ST                0
 Number of vessels fluro    0
 Thallium                   0
 dtype: int64)

In [34]:
train[train.duplicated()],test[test.duplicated()]

(Empty DataFrame
 Columns: [id, Age, Sex, Chest pain type, BP, Cholesterol, FBS over 120, EKG results, Max HR, Exercise angina, ST depression, Slope of ST, Number of vessels fluro, Thallium, Heart Disease]
 Index: [],
 Empty DataFrame
 Columns: [id, Age, Sex, Chest pain type, BP, Cholesterol, FBS over 120, EKG results, Max HR, Exercise angina, ST depression, Slope of ST, Number of vessels fluro, Thallium]
 Index: [])

In [35]:
train.head()

,id,Age,Sex,Chest pain type,BP,Cholesterol,FBS over 120,EKG results,Max HR,Exercise angina,ST depression,Slope of ST,Number of vessels fluro,Thallium,Heart Disease
0,0,58,1,4,152,239,0,0,158,1,3.6,2,2,7,Presence
1,1,52,1,1,125,325,0,2,171,0,0.0,1,0,3,Absence
2,2,56,0,2,160,188,0,2,151,0,0.0,1,0,3,Absence
3,3,44,0,3,134,229,0,2,150,0,1.0,2,0,3,Absence
4,4,58,1,4,140,234,0,2,125,1,3.8,2,3,3,Presence

In [36]:
#Setting Target-Category -->0/1
train['Heart Disease']=train['Heart Disease'].map({'Absence':0, 'Presence':1})

# id is Not That much important feature So Remove it
train.drop('id',axis=1,inplace=True)

testID=test.pop('id')

y=train.pop('Heart Disease')

One Hot Encoding

In [37]:
oh_cols=train.columns.to_list()
oh = OneHotEncoder(handle_unknown='ignore', sparse_output=False)

oh_train=pd.DataFrame(oh.fit_transform(train[oh_cols]))
train[oh.get_feature_names_out(train[oh_cols].columns)] = oh_train.astype(int)

oh_test= pd.DataFrame(oh.transform(test[oh_cols]))
test[oh.get_feature_names_out(test[oh_cols].columns)] = oh_test.astype(int)

In [38]:
oh_train

,0,1,2,3,4,5,6,7,8,9,...,430,431,432,433,434,435,436,437,438,439
0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
629995,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0
629996,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0
629997,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0
629998,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0
629999,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0

Sclaing a Data using Standerd Scaler

In [39]:
scaler=StandardScaler()

#Scale A Train Data
scaled_train=pd.DataFrame(scaler.fit_transform(train))
scaled_train.columns=train.columns

## Scale A Test Data
scaled_test=pd.DataFrame(scaler.fit_transform(test))
scaled_test.columns=test.columns

In [40]:
scaled_train

,Age,Sex,Chest pain type,BP,Cholesterol,FBS over 120,EKG results,Max HR,Exercise angina,ST depression,...,Slope of ST_1,Slope of ST_2,Slope of ST_3,Number of vessels fluro_0,Number of vessels fluro_1,Number of vessels fluro_2,Number of vessels fluro_3,Thallium_3,Thallium_6,Thallium_7
0,0.467921,0.631760,0.806994,1.435822,-0.178490,-0.294858,-0.982858,0.271190,1.628894,3.040655,...,-1.148335,1.207838,-0.158778,-1.556068,-0.452259,3.256005,-0.194028,-1.201903,-0.133097,1.246279
1,-0.258797,0.631760,-2.715729,-0.367088,2.374837,-0.294858,1.019582,0.951359,-0.613913,-0.754928,...,0.870826,-0.827926,-0.158778,0.642646,-0.452259,-0.307125,-0.194028,0.832014,-0.133097,-0.802388
2,0.225682,-1.582881,-1.541488,1.970017,-1.692672,-0.294858,1.019582,-0.095054,-0.613913,-0.754928,...,0.870826,-0.827926,-0.158778,0.642646,-0.452259,-0.307125,-0.194028,0.832014,-0.133097,-0.802388
3,-1.227755,-1.582881,-0.367247,0.233882,-0.475388,-0.294858,1.019582,-0.147375,-0.613913,0.299400,...,-1.148335,1.207838,-0.158778,0.642646,-0.452259,-0.307125,-0.194028,0.832014,-0.133097,-0.802388
4,0.467921,0.631760,0.806994,0.634529,-0.326939,-0.294858,1.019582,-1.455391,1.628894,3.251520,...,-1.148335,1.207838,-0.158778,-1.556068,-0.452259,-0.307125,5.153899,0.832014,-0.133097,-0.802388
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
629995,0.225682,-1.582881,-2.715729,-1.368705,-0.564458,-0.294858,-0.982858,-1.089147,-0.613913,-0.754928,...,0.870826,-0.827926,-0.158778,0.642646,-0.452259,-0.307125,-0.194028,-1.201903,-0.133097,1.246279
629996,-0.016558,0.631760,0.806994,-0.166765,0.118409,3.391458,1.019582,-0.147375,-0.613913,-0.754928,...,-1.148335,1.207838,-0.158778,0.642646,-0.452259,-0.307125,-0.194028,0.832014,-0.133097,-0.802388
629997,1.557998,0.631760,0.806994,-0.033216,0.890344,-0.294858,-0.982858,-0.199696,-0.613913,-0.754928,...,0.870826,-0.827926,-0.158778,-1.556068,-0.452259,3.256005,-0.194028,-1.201903,-0.133097,1.246279
629998,-0.258797,0.631760,0.806994,0.634529,-1.366083,-0.294858,1.019582,0.218870,-0.613913,-0.754928,...,0.870826,-0.827926,-0.158778,0.642646,-0.452259,-0.307125,-0.194028,-1.201903,7.513342,-0.802388
629999,-0.379917,-1.582881,-1.541488,-0.033216,-1.366083,-0.294858,-0.982858,0.794397,-0.613913,-0.754928,...,0.870826,-0.827926,-0.158778,0.642646,-0.452259,-0.307125,-0.194028,0.832014,-0.133097,-0.802388

Apply Model Training Tecnique

1)Logistic regression

In [ ]:
model=LogisticRegression()

kf=KFold(n_splits=5)
train_label=pd.Series(index=scaled_train.index)


for train_index,test_index in kf.split(scaled_train):
    model.fit(scaled_train.iloc[train_index], y.iloc[train_index])
    pred=model.predict_proba(scaled_train.iloc[test_index])[:,1]
    train_label.iloc[test_index]=pred
    
model.fit(scaled_train, y)
test_label=pd.Series(model.predict_proba(scaled_test)[:,1])
scaled_train['label']=train_label
scaled_test['label']=test_label

2)XGBoost

In [41]:
model2=XGBClassifier(n_estimators=1200,subsample = 0.7973179062433801,
                     colsample_bytree = 0.7369809154998354, 
                     max_depth=3, device='cuda', learning_rate=0.01, random_state=6)
score = cross_val_score(model2, scaled_train, y, cv=5, scoring='roc_auc') # CV Score
print("CV:",score.mean())

CV: 0.9544979245131285

In [42]:
model2.fit(scaled_train, y) 
pred = model2.predict_proba(scaled_test)[:,1]

In [43]:
final = pd.DataFrame({'id':testID, 'Heart Disease':pred})
final.to_csv('submission.csv', index=False)